# Generated by Django 2.0.7 on 2018-07-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_auto_20180713_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='progression',
            name='chords',
            field=models.ManyToManyField(related_name='chords', to='logic.Chord'),
        ),
    ]
